import {getSupabaseAdmin} from './supabase';
export async function upsertUser(u:{email:string;name?:string|null;image?:string|null;googleSubject?:string|null}){const {data,error}=await getSupabaseAdmin().from('users').upsert({email:u.email,name:u.name,image:u.image,google_subject:u.googleSubject},{onConflict:'email'}).select().single();if(error)throw error;return data}
export async function createScan(userId:string,i:{spreadsheetId:string;gid:string;sheetUrl:string;accessTokenHash?:string|null}){const {data,error}=await getSupabaseAdmin().from('scan_jobs').insert({user_id:userId,spreadsheet_id:i.spreadsheetId,gid:i.gid,sheet_url:i.sheetUrl,access_token_hash:i.accessTokenHash??null}).select().single();if(error)throw error;return data}
export async function getScan(id:string,userId?:string){let q=getSupabaseAdmin().from('scan_jobs').select('*').eq('id',id);if(userId)q=q.eq('user_id',userId);const {data,error}=await q.single();if(error)throw error;return data}
export async function getScanPublic(id:string,token:string){const {data,error}=await getSupabaseAdmin().from('scan_jobs').select('*').eq('id',id).single();if(error)throw error;const crypto=await import('node:crypto');if(!data.access_token_hash||crypto.createHash('sha256').update(token).digest('hex')!==data.access_token_hash)throw new Error('Unauthorized');return data}
export const addScanDocuments=async(scanId:string,docs:{id:string}[])=>{const db=getSupabaseAdmin();if(docs.length)await db.from('scan_documents').upsert(docs.map((d,i)=>({scan_id:scanId,document_id:d.id,ordinal:i})));const {error}=await db.from('scan_jobs').update({total_documents:docs.length,status:'running',started_at:new Date().toISOString()}).eq('id',scanId);if(error)throw error}
export async function createOrGetDocument(userId:string,i:{url:string;canonicalUrl?:string;filename?:string;sourceKind?:string}){const {data,error}=await getSupabaseAdmin().from('documents').upsert({user_id:userId,source_url:i.url,canonical_url:i.canonicalUrl??i.url,filename:i.filename,source_kind:i.sourceKind},{onConflict:'user_id,canonical_url'}).select().single();if(error)throw error;return data}
export const replaceQuestions=async(documentId:string,qs:any[])=>{const db=getSupabaseAdmin();await db.from('questions').delete().eq('document_id',documentId);if(qs.length){const {error}=await db.from('questions').insert(qs.map(q=>({document_id:documentId,question_number:q.questionNumber,page_number:q.pageNumber,raw_text:q.rawQuestionText,normalized_text:q.questionText,options_json:q.options,answer:q.answer??null,section:q.section??null,subject:q.subject??null,question_type:q.questionType??null,numeric_features:q.numericFeatures})));if(error)throw error}await db.from('documents').update({question_count:qs.length}).eq('id',documentId)};
export const saveDocumentProcessing=async(documentId:string,d:any)=>{const {error}=await getSupabaseAdmin().from('documents').update({content_hash:d.hash,file_size:d.size,storage_path:d.storagePath,page_count:d.pageCount,status:d.status,processing_error:d.error??null,updated_at:new Date().toISOString()}).eq('id',documentId);if(error)throw error};
export const saveEmbedding=async(q:string,e:number[],p:string,m:string)=>{const {error}=await getSupabaseAdmin().from('question_embeddings').upsert({question_id:q,embedding:e,provider:p,model:m});if(error)throw error};
export const findEmbeddingCandidates=async(scanId:string,q:string,limit=25,threshold=.55)=>{const {data,error}=await getSupabaseAdmin().rpc('find_embedding_candidates',{p_scan_id:scanId,p_question_id:q,p_limit:limit,p_threshold:threshold});if(error)throw error;return data??[]};
export const saveMatch=async(scanId:string,a:string,b:string,s:any,d:any,payload?:unknown)=>{const [qa,qb]=a<b?[a,b]:[b,a];const {error}=await getSupabaseAdmin().from('similarity_matches').upsert({scan_id:scanId,question_a_id:qa,question_b_id:qb,lexical_score:s.lexical,semantic_score:s.semantic,numeric_score:s.numeric,structure_score:s.structure,final_score:s.final,category:d.category,confidence:d.confidence,reason:d.reason,verified_by_llm:d.verifiedByLlm,verifier_payload:payload??null},{onConflict:'scan_id,question_a_id,question_b_id'});if(error)throw error};
export const bumpScan=async(id:string,p:any)=>{const {error}=await getSupabaseAdmin().from('scan_jobs').update(p).eq('id',id);if(error)throw error}; export const addError=async(scanId:string,docId:string|null,stage:string,message:string,details?:unknown)=>{await getSupabaseAdmin().from('processing_errors').insert({scan_id:scanId,document_id:docId,stage,message,details:details??null})};
export const getScanMatches=async(id:string)=>{const {data,error}=await getSupabaseAdmin().from('similarity_matches').select('*,question_a:questions!question_a_id(*,documents(*)),question_b:questions!question_b_id(*,documents(*))').eq('scan_id',id).order('final_score',{ascending:false});if(error)throw error;return data??[]};
export const getScanDocuments=async(id:string)=>{const {data,error}=await getSupabaseAdmin().from('scan_documents').select('ordinal,documents(*)').eq('scan_id',id).order('ordinal');if(error)throw error;return data??[]}; export const getScanQuestions=async(id:string)=>{const db=getSupabaseAdmin();const s=await db.from('scan_documents').select('document_id').eq('scan_id',id);const {data,error}=await db.from('questions').select('*,documents!inner(id,filename,source_url)').in('document_id',(s.data??[]).map(x=>x.document_id));if(error)throw error;return data??[]};
