import type { NumericFeatures,ParsedQuestion } from '../../types';
const Q=/(?:^|\s)(?:Q(?:uestion)?\.?\s*(\d{1,3})[.)]?\s+|(\d{1,3})[.)]\s+)/gim; const OPTION=/(?:^|\s)[(\[]?([A-Ea-e])[)\].:-]?\s*/g;
export function isLikelyCandidateQuestion(t:string){const x=t.trim();return !!x&&!/^(answer\s*key|answers|solutions?|hints?\s*&?\s*solutions?|explanations?)\b/i.test(x)}
export function splitPageIntoQuestionBlocks(pageNumber:number,text:string){const m=[...text.matchAll(Q)];return m.map((x,i)=>({questionNumber:x[1]??x[2],pageNumber,text:text.slice(x.index!+x[0].length,m[i+1]?.index??text.length).trim()})).filter(x=>isLikelyCandidateQuestion(x.text))}
const clean=(t:string)=>t.replace(/\b(?:answer\s*key|solutions?|hints?\s*&?\s*solutions?)\b[\s\S]*$/i,'').trim();
function options(body:string){const m=[...body.matchAll(OPTION)],starts=m.map(x=>x.index!).filter(x=>x>=0);if(!starts.length)return {question:body,options:[] as string[]};return {question:body.slice(0,starts[0]).trim(),options:starts.map((s,i)=>body.slice(s,starts[i+1]??body.length).replace(OPTION,'').trim())}}
export function extractNumericFeatures(text:string):NumericFeatures{const numbers=[...text.matchAll(/(?<![A-Za-z])[-+]?\d+(?:\.\d+)?/g)].map(x=>Number(x[0])).filter(Number.isFinite);const percentages=[...text.matchAll(/[-+]?\d+(?:\.\d+)?\s*%/g)].map(x=>Number(x[0].replace('%','')));const ratios=[...text.matchAll(/\b\d+(?:\.\d+)?\s*:\s*\d+(?:\.\d+)?\b/g)].map(x=>x[0].replace(/\s+/g,''));const units=[...text.matchAll(/\b(?:km\/h|m\/s|km|m|cm|mm|kg|g|litre|liter|l|ml|sec|s|min|hr|hour|days?|years?|months?|degrees?|°|rupees?|rs\.?|₹)\b/gi)].map(x=>x[0].toLowerCase());const variables=[...new Set([...text.matchAll(/\b[a-zA-Z](?:_[a-zA-Z0-9]+)?\b/g)].map(x=>x[0]).filter(x=>x.length<=3&&!/^(the|and|find|per)$/i.test(x)))];const equations=text.match(/[^.?!\n]{0,50}(?:=|≤|≥|<|>)[^.!?\n]{0,80}/g)?.map(x=>x.trim())??[];const operators=[...new Set(text.match(/[+\-*/^≤≥=<>()]/g)??[])];return {numbers,percentages,ratios,units,variables,equations,operators}}
export function normalizeQuestion(text:string){return text.normalize('NFKC').toLowerCase().replace(/^\s*(?:q(?:uestion)?\.?\s*)?\d{1,3}[.)]?\s*/i,'').replace(/https?:\/\/\S+/g,' ').replace(/\s+/g,' ').replace(/\s+([,.;:?])/g,'$1').trim()}
export function inferSubject(text:string){const r:[string,RegExp][]=[['time_speed_distance',/train|speed|distance|km\/h|boat|stream/i],['profit_loss',/profit|loss|discount|marked price/i],['percentage',/percent|%/i],['ratio',/ratio|proportion/i],['time_work',/work(?:er|ers)?|pipe|cistern/i],['probability',/probability|chance|dice|cards?/i],['permutation_combination',/permutation|combination|arrange|select/i],['algebra',/equation|quadratic|variable|roots?|polynomial/i],['geometry',/area|perimeter|triangle|circle|square|rectangle/i],['arithmetic',/average|mean|number|integer|fraction|divisible/i]];return r.find(([,re])=>re.test(text))?.[0]??'other'}
export function parseQuestions(documentId:string,pdfName:string,pdfUrl:string,pages:{pageNumber:number;text:string}[]):ParsedQuestion[]{const out:ParsedQuestion[]=[];let solutionSection=false;for(const p of pages){const head=p.text.slice(0,350);if(/^(?:answer\s*key|answers?|solutions?|hints?\s*&?\s*solutions?|explanations?)\b/i.test(head)||/\b(?:answer\s*key|hints?\s*&?\s*solutions?|detailed\s+solutions?)\b/i.test(head)){solutionSection=true;continue}if(solutionSection)continue;for(const b of splitPageIntoQuestionBlocks(p.pageNumber,p.text)){const {question,options:opts}=options(clean(b.text));const q=normalizeQuestion(question);if(!q)continue;out.push({documentId,pdfName,pdfUrl,questionNumber:b.questionNumber,pageNumber:p.pageNumber,rawQuestionText:b.text,questionText:q,options:opts,subject:inferSubject(question),questionType:inferSubject(question),numericFeatures:extractNumericFeatures(question)})}}return out}
